# Supabase local development configuration
project_id = "mathquest"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://mathquest.mainuddintalukdar.cloud", "http://localhost:3000/**"]
jwt_expiry = 3600
enable_signup = true

[analytics]
enabled = false
